### ISSUE TITLE
Token auth for Jira?

### ISSUE THREAD

**Issue by mvarela** [PositiveTechnologies/flower#100]
Hi,
  I just came across your library yesterday, and it looks awesome! I'm trying to use it against Jira running on the Atlassian cloud, and it seems it's not possible, since the basic auth has been deprecated, and Flower does not support token-based auth for Jira. 
How would I go about implementing this functionality?

**Comment by profitware** [comment]
Hi @mvarela ,

Thank you for your interest. Originally the integration was done for on-prem version of Jira, so dependecies were intentionally frozen to the version which supports one without token auth. Not to break things I propose to do what you need the following way:

1. Copy `flower-integration-jira` to something like `flower-integration-atlassian-cloud`
2. Modify dependency versions within `flower-integration-atlassian-cloud` and add/modify needed code (be aware of these: https://github.com/PositiveTechnologies/flower/issues/95#issuecomment-513488125 )
3. Add `flower-integration-atlassian-cloud` to `:sub` of the `flower` parent `project.clj` but not to the `:dependencies` (as this might blow things up)
4. Add links to `flower-integration-atlassian-cloud` from `checkouts` and `flower-tracker/checkouts` directories of `flower` project.
5. Within your project specify only `flower` dependencies you need (yes, microkernel):

```
[flower/flower-tracker "0.4.8-SNAPSHOT"]
[flower/flower-integration-atlassian-cloud "0.4.8-SNAPSHOT"]
```

(0.4.8-SNAPSHOT has not been built yet, but it will be the same as release version)

You can always use local copy of `flower` for development by adding links to needed subpackages to the `checkouts` folder of your project.

I'm sorry I cannot implement this myself for a number of reasons, but I can answer your questions if some arise during your journey into this.

Thank you.

**Comment by profitware** [comment]
This file is also needs to be modified to handle tokens: https://github.com/PositiveTechnologies/flower/blob/master/flower-common/src/flower/macros.clj#L36

**Comment by profitware** [comment]
Ah, also tracker type automatic definition and tests nearby: https://github.com/PositiveTechnologies/flower/blob/master/flower-tracker/src/flower/tracker/core.clj#L94

**Comment by mvarela** [comment]
Thanks, Sergey, I'll give this a try!
