### ISSUE TITLE
Jira dependencies are outdated

### ISSUE THREAD

**Issue by profitware** [PositiveTechnologies/flower#95]
Dependencies for Jira integration are outdated. Need to be updated.

```
bash-3.2$ cat project.clj 
(defproject jira-needs-update "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [flower/flower-integration-jira "0.4.6"]])
bash-3.2$ lein deps
Could not find artifact com.atlassian.fugue:fugue:jar:2.6.1 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.atlassian.fugue:fugue:jar:2.6.1 in clojars (https://repo.clojars.org/)
Could not find artifact com.atlassian.fugue:fugue:jar:2.6.1 in atlassian-public (https://maven.atlassian.com/content/repositories/atlassian-public/)
Could not find artifact com.atlassian.fugue:fugue:jar:2.6.1 in eclipse-releases (https://repo.eclipse.org/content/groups/releases/)
Could not find artifact com.atlassian.platform:platform:pom:3.1.7 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.atlassian.platform:platform:pom:3.1.7 in central (https://repo1.maven.org/maven2/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Comment by lvh** [comment]
Looks like this was force downgraded in this commit: https://github.com/PositiveTechnologies/flower/commit/9d859ed1b8e91b1bfd36ed61f9b9c01afc23bc77

Any idea why? Does the new client not throw exceptions anymore?

**Comment by profitware** [comment]
> Looks like this was force downgraded in this commit: [9d859ed](https://github.com/PositiveTechnologies/flower/commit/9d859ed1b8e91b1bfd36ed61f9b9c01afc23bc77)
> 
> Any idea why? Does the new client not throw exceptions anymore?

I had got something in my mind when downgrading and locking versions but I cannot recall the concrete reason (probably, some incompatibilities in Jira SDK itself or something like that - as you can see, in this exact commit not only exception handling was added, but also `createWithBasicHttpAuthentication` method used to connect to Jira API - my fault). I think I may just try upgrade versions and watch where (if) it brokes when I have spare time (may be this weekend?)

**Comment by profitware** [comment]
So, the problem is as follows: when upgrading to `[com.atlassian.jira/jira-rest-java-client-core "5.1.0"]` and `[com.atlassian.jira/jira-rest-java-client-core "5.1.0"]` not only it starts to require not the newest `[com.atlassian.util.concurrent/atlassian-util-concurrent "3.0.0"]` to use `com.atlassian.util.concurrent` but it also uses `io.atlassian` namespaces internally - looks like dependency hell. The solution is to change alassian public repository to caching one here: https://packages.atlassian.com/content/groups/public/ where older versions still exist.

**Comment by danirukun** [comment]
Hi, any update on this issue?

**Comment by profitware** [comment]
> Hi, any update on this issue?

Hi @DaniruKun ,

As for this concrete issue, it was merged into develop and built as 0.4.7-SNAPSHOT last year, see: https://clojars.org/flower/versions/0.4.7-SNAPSHOT

As for releasing this, well, I'm now working for another company for a while, thus I cannot afford myself to spend working time for that. I think along with @harlov we might spend some spare time this or next Sunday in order to release new version (but no guarantee yet).

Thank you for your interest.

**Comment by profitware** [comment]
@DaniruKun please check if 0.4.7 release version works for you. Thank you.

**Comment by danirukun** [comment]
Yes, looks good, thank you 👍
